// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCnlaYxA8U6rCeWYJzXcc6REKKhncxeUU',
    appId: '1:412871467998:web:354610b7fd7e9dfcdc734f',
    messagingSenderId: '412871467998',
    projectId: 'personal-assistance-f1460',
    authDomain: 'personal-assistance-f1460.firebaseapp.com',
    storageBucket: 'personal-assistance-f1460.appspot.com',
    measurementId: 'G-WT7TXM2290',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ7mDSYysEtj5T0tGsXIjtATdEEeUzaMM',
    appId: '1:412871467998:android:07d7c4d974dcfb08dc734f',
    messagingSenderId: '412871467998',
    projectId: 'personal-assistance-f1460',
    storageBucket: 'personal-assistance-f1460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbQUD16wUrN9Iu59mB0iccS5Z7dsNP8zg',
    appId: '1:412871467998:ios:92634c2df0d4e02fdc734f',
    messagingSenderId: '412871467998',
    projectId: 'personal-assistance-f1460',
    storageBucket: 'personal-assistance-f1460.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbQUD16wUrN9Iu59mB0iccS5Z7dsNP8zg',
    appId: '1:412871467998:ios:92634c2df0d4e02fdc734f',
    messagingSenderId: '412871467998',
    projectId: 'personal-assistance-f1460',
    storageBucket: 'personal-assistance-f1460.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCnlaYxA8U6rCeWYJzXcc6REKKhncxeUU',
    appId: '1:412871467998:web:9f6901cc17997775dc734f',
    messagingSenderId: '412871467998',
    projectId: 'personal-assistance-f1460',
    authDomain: 'personal-assistance-f1460.firebaseapp.com',
    storageBucket: 'personal-assistance-f1460.appspot.com',
    measurementId: 'G-2V28XXYEXC',
  );
}
